# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  filetype: #extension
    description: 'Filetypes to process'
    required: true
    default: 'png'
outputs:
  time: #id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ github.workspace }} ${{ inputs.filetype }}